config/routes.rb
Rails.application.routes.draw do
  root 'gig#index'
  devise_for :users, skip: :all
  devise_scope :user do
    devise_scope :user do
    get  '/users/sign_in'  => 'devise/sessions#new', as: :user_session
    post   '/users/sign_in'  => 'devise/sessions#create', as: :new_user_session
    delete '/users/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    # post  '/users/password'  => 'devise/passwords#create', as: :user_password
    # put   '/users/password'  => 'devise/passwords#update', as: nil
    patch '/users/password'  => 'devise/passwords#update', as: :new_password
     get  '/users/sign_up' =>   'devise/registrations#new', as: :new_user_registration
     get '/users/edit' =>  'devise/registrations#edit', as: :edit_user_registration
     patch '/users' =>  'devise/registrations#update', as: :user_registration
     put  '/users' => 'devise/registrations#update'
     delete '/users' => 'devise/registrations#destroy'
     post '/users'=> 'devise/registrations#create'
     get '/users/:id'  => 'users#show', as: :user
    end
  end

  resources :gig, only: [:index, :show]
  resources :instruments, only: [:index, :new, :show, :create]

  namespace :api do
        namespace :v1 do
            resources :users, only: [:index, :show, :new, :create]
        end
    end
    namespace :api do
          namespace :v1 do
              resources :instruments, only: [:index, :show, :new, :create]
          end
      end
  end
#end
    # namespace :api do
    #       namespace :v1 do
    #           resources :instruments, only: [:index, :show, :new, :create]
    #       end
    #   end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gig.rb
class User < ApplicationRecord


end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :instrument_joins
  has_many :users, through: :instrument_joins
end

app/models/instrument_join.rb
class InstrumentJoin < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
 end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :profile_photo, ProfilePhotoUploader

   has_many :instrument_joins
   has_many :instruments, through: :instrument_joins
end

app/controllers/api/v1/gig_controller.rb
class Api::V1::GigsController < ApplicationController
  def index
    render json: User.all
    render json: Instrument.all
  end

  def show
    render json: User.find(params[:id])
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    render json: User.all
  end

  def show
    render json: User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :city, :state, :zip, :description, :soundcloud_link, :recordings_link, :rate_per_gig, :rate_per_hour, :profile_photo, :instrument ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :profile_photo, :city, :state, :zip, :description, :soundcloud_link, :recordings_link, :rate_per_gig, :rate_per_hour, :instrument])
  end
end

app/controllers/gig_controller.rb
class GigController < ApplicationController

  def index
    @users = User.all
    @user_sample = @users.sample(1)
    @instruments = Instrument.all
    @instrument_join = InstrumentJoin.all
    @instrument_list = {brass:
                          ["Trumpet",
                          "Cornet",
                          "Piccolo Trumpet",
                          "Flugelhorn",
                          "French horn",
                          "Baritone horn",
                          "Euphonium",
                          "Alto horn",
                          "Tenor horn",
                          "Trombone",
                          "Tuba",
                          "Bugle"
                        ],


                          keyboard:
                            ["Accordion",
                            "Celesta",
                            "Clavichord",
                            "Dulcitone",
                            "Electronic keyboard",
                            "harpsichord",
                            "Organ",
                            "Piano",
                            "Synthesizer"
                          ],

                          strings:
                            ["violin",
                            "viola",
                            "cello",
                            "string bass",
                            "harp"
                          ],

                          guitar:
                            ["acoustic guitar",
                            "banjo",
                            "bass guitar",
                            "electric guitar",
                            "mandolin",
                            "ukulele"
                          ],

                          woodwinds:
                            ["alto flute",
                            "oboe",
                            "bass oboe",
                            "bassoon",
                            "clarinet",
                            "contrabass oboe",
                            "flute",
                            "piccolo",
                            "recorder",
                            "saxophone"
                          ],

                          percussion: [
                            "bass drum",
                            "bongo drum",
                            "castanet",
                            "conga",
                            "cymbal",
                            "djembe",
                            "drums",
                            "gong",
                            "maracas",
                            "marimba",
                            "snare drum",
                            "tambourine",
                            "timpani",
                            "glockenspiel"
                          ]
                        }
          end
          def show
            @users = Users.all
            @user = User.find(params[:id])
        end
      end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

      def index
        @instruments= Instrument.all
      end

      def show
        @instrument = Instrument.find(params[:id])
        @users = @instrument.users
      end
    end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
  end

  def new
    @user = User.new
    @instruments = Instrument.all
  end

  def create
     user_email = params[:session][:email]
     user_password = params[:session][:password]
     user = user_email.present? && User.find_by(email: user_email)
     if user.valid_password?(user_password)
       sign_in user, store: true
       render json: user, status: 200, location: [:api, user]
     else
       render json: { errors: "Invalid email or password" }, status: 422
     end
  end

  def edit
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)

    else
      render 'edit'
  end
end


  private

  def new_user_ params
    params.require(:users).permit(:first_name, :last_name, :city, :state, :zip, :description, :rate_per_gig, :rate_per_hour, :soundcloud_link, :recordings_link, :profile_photo, :instrument)
  end

  def sign_in_ params
    params.require(:users).permit(:email, :encrypted_password)
  end

end

app/views/gig/index.html.erb
  <h1 id="home"> Gig </h1>
  <h2 id="choose">Choose your musician by...</h2>
  <div class="main-nav">
    <div id="home-page-navigation" class="column panel callout small-9 small-centered">
      <h1> <%= link_to 'Instruments', instruments_path %> </h1>
    </div>
    <div id="home-page-navigation" class="column panel callout small-9 small-centered">
      <h1> <%= link_to 'Genres', instruments_path %> </h1>
    </div>
  </div>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/instruments/index.html.erb
<div id="instrument">

<h1 id="title"class="text-center"> Instruments</h1></div>
<div id="menu">

<div class="dropdown">
   <p id="brass" class="column panel callout small-9 small-centered">Brass</p>
  <%@instruments.each do |instrument| %>
    <%if instrument.instrument_type === 'brass' %>
    <div id="dropdown-content" class="column panel callout small-9 small-centered">
      <p><%= link_to instrument.name, instrument_path(instrument)%></p>
    </div>
  <%end%>
<%end%>
</div>

<div class="dropdown">
<p id="strings" class="column panel callout small-9 small-centered">Strings</p>
 <%@instruments.each do |instrument| %>
   <%if instrument.instrument_type === 'orchestral strings' %>
   <div id="dropdown-content" class="column panel callout small-9 small-centered">
     <p><%= link_to instrument.name, instrument_path(instrument)%></p>
 </div>
 <%end%>
<%end%>
</div>

<div class="dropdown">
<p id="guitar" class="column panel callout small-9 small-centered">Guitar</p>
 <%@instruments.each do |instrument| %>
   <%if instrument.instrument_type === 'guitar family' %>
   <div id="dropdown-content" class="column panel callout small-9 small-centered">
     <p><%= link_to instrument.name, instrument_path(instrument)%></p>
 </div>
 <%end%>
<%end%>
</div>

<div class="dropdown">
  <p id="woodwinds" class="column panel callout small-9 small-centered">Woodwinds</p>

 <%@instruments.each do |instrument| %>
   <%if instrument.instrument_type === 'woodwinds' %>
   <div id="dropdown-content" class="column panel callout small-9 small-centered">
     <p><%= link_to instrument.name, instrument_path(instrument)%></p>
 </div>
 <%end%>
<%end%>
</div>

<div class="dropdown">
  <p id="percussion" class="column panel callout small-9 small-centered">Percussion</p>
  <%@instruments.each do |instrument| %>
  <%if instrument.instrument_type === 'percussion' %>
    <div  id="dropdown-content" class="column panel callout small-9 small-centered">
      <p><%= link_to instrument.name, instrument_path(instrument)%></p>
    </div>
  <%end%>
  <%end%>
</div>
</div>

app/views/instruments/show.html.erb
<h1 id="individual-instrument" class="text-center"><%= @instrument.name %></h1>
  <div id="list-page" class="column panel callout small-9 small-centered">
    <%User.all.each do |user|%>
      <%user.instruments.each do |piece|%>
        <%if piece.name === "#{@instrument.name}" %>
        <div class="user-tab">
            <img class="image-tile" src="<%=user.profile_photo.url%>"</img>
            <p class="name-tile"><%= link_to user.first_name, user_path(user)%> <%= link_to user.last_name, user_path(user) %></p>
            <p id="description-tile" class="description-tile"><%=user.description%></p>
          </div>
        <%end%>
      <%end%>
    <%end%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gig</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "application"  %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <link href="https://fonts.googleapis.com/css?family=Neucha&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Gig</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="left">
        <li class="name">
          <h1> <%= link_to 'Instruments', instruments_path %> </h1>
        </li>
        <li class="name">
          <h1> <%= link_to 'Genres', instruments_path %> </h1>
        </li>
      </ul>
    </section>

        <section class="top-bar-section">
          <ul class="right">
            <%- if user_signed_in? -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', user_session_path %></li>
            <%- end -%>
          </ul>
        </section>
      </nav>

      <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
      <%- end -%>

      <%= yield %>

      <%= javascript_include_tag 'application' %>

      <%- if Rails.env.development? || Rails.env.test? -%>
      <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
      <%- end -%>
      <%- end -%>
      <%= javascript_pack_tag 'application' %>

      <%= yield :extra_footer %>
    </body>
    </html>

app/views/users/show.html.erb
<div id="app">

</div>